# Generated by Django 4.2.1 on 2023-05-25 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First_Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last_Name')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_origin', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='News_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('excerpt', models.CharField(max_length=150, verbose_name='Excerpt')),
                ('post_field', models.TextField(verbose_name='Post_Field')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_site.author')),
                ('site_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_site.site', verbose_name='')),
                ('tag', models.ManyToManyField(to='news_site.tag')),
            ],
        ),
    ]
