# Generated by Django 4.1.7 on 2023-05-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news_post',
            name='slug',
            field=models.SlugField(default='sisi', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news_post',
            name='site_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_site.site', verbose_name='Site_Origin'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_origin',
            field=models.CharField(max_length=100, verbose_name='Site_Country'),
        ),
    ]
