# Generated by Django 4.1.7 on 2023-05-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0002_news_post_date_news_post_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_Post',
            new_name='NewsPost',
        ),
    ]
