# Generated by Django 4.2.1 on 2023-05-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0003_rename_news_post_newspost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPost',
            new_name='Post',
        ),
    ]
