# Generated by Django 4.1.7 on 2023-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0004_rename_newspost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='cheese'),
        ),
    ]
