# Generated by Django 4.1.7 on 2023-06-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0008_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='news_site.tag'),
        ),
    ]
