# Generated by Django 4.2.1 on 2023-06-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0009_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
