# Generated by Django 4.1.7 on 2023-07-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0011_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
