# Generated by Django 4.1.7 on 2023-07-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0012_remove_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
