# Generated by Django 4.1.7 on 2023-07-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0013_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
        migrations.AddField(
            model_name='author',
            name='author_desc',
            field=models.CharField(default='', max_length=50, verbose_name='Author_Decription'),
        ),
    ]
