# Generated by Django 4.1.7 on 2023-07-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0014_remove_author_country_author_author_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_desc',
            field=models.CharField(default='', max_length=500, verbose_name='Author_Decription'),
        ),
    ]
