# Generated by Django 4.1.7 on 2023-07-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0015_alter_author_author_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
