# Generated by Django 4.2.1 on 2023-10-27 23:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0016_remove_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_field',
            field=ckeditor.fields.RichTextField(verbose_name='Post_Field'),
        ),
    ]
